"""document progress column

Revision ID: 06e9ecb4e9b3
Revises: 713fc1034df5
Create Date: 2026-08-11 09:54:19.506739
"""
from alembic import op
import sqlalchemy as sa


revision = '06e9ecb4e9b3'
down_revision = '713fc1034df5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
