"""inventory items

Revision ID: 713fc1034df5
Revises: d8304ea54679
Create Date: 2026-07-29 17:41:00.251830
"""
from alembic import op
import sqlalchemy as sa


revision = '713fc1034df5'
down_revision = 'd8304ea54679'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('composition', sa.String(length=255), nullable=True),
    sa.Column('strength', sa.String(length=64), nullable=True),
    sa.Column('pack', sa.String(length=64), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('stock_qty', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_composition'), ['composition'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index('ix_inventory_shop_norm', ['shop_id', 'normalized_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_shop_norm')
        batch_op.drop_index(batch_op.f('ix_inventory_items_shop_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_composition'))

    op.drop_table('inventory_items')
    # ### end Alembic commands ###
