"""initial schema

Revision ID: d8304ea54679
Revises: 
Create Date: 2026-07-27 17:16:37.549808
"""
from alembic import op
import sqlalchemy as sa


revision = 'd8304ea54679'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_shop_id'), ['shop_id'], unique=False)

    op.create_table('shops',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connectors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connectors_shop_id'), ['shop_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_shop_id'), ['shop_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('shop_id', sa.String(length=32), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('image_ref', sa.String(length=512), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('push_deliveries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('connector_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_deliveries_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_deliveries_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_deliveries_idempotency_key'), ['idempotency_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_deliveries_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_push_deliveries_document_id'))
        batch_op.drop_index(batch_op.f('ix_push_deliveries_connector_id'))

    op.drop_table('push_deliveries')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_shop_id'))

    op.drop_table('documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_shop_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connectors_shop_id'))

    op.drop_table('connectors')
    op.drop_table('shops')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_shop_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
